Fix typo in writing_tools.py
rmc crashing when converting to SVG. Traceback shows error "AttributeError: type object 'Pen' has no attribute 'ERASE_AREA'"